### PR TITLE
fix nats

### LINKED ISSUE #320: fix nat.js
```
make -C tests/lib-num run-test 
make: Entering directory `/usr/local/home/hheuzard/js_of_ocaml/tests/lib-num'
ocamlc nums.cma test.ml test_nats.ml test_big_ints.ml test_ratios.ml test_nums.ml test_io.ml -o test_num.byte
File "test_nats.ml", line 112, characters 2-12:
Warning 3: deprecated: String.set
Use Bytes.set instead.
../../compiler/js_of_ocaml ../../runtime/nat.js test_num.byte
node test_num.js

num_digits_nat
 -1...
 0...
 1...

length_nat
 1...

equal_nat
 1...
 2...
 3...
 4...

incr_nat
 1...
 2...
 3...
 4...

decr_nat
 1...
 2...
 3...
 4...

is_zero_nat
 1...
 2...
 3...
 4...

string_of_nat
 1...
 2...

string_of_nat && nat_of_string
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...
 18...
 19...
 20...
 21...
 22...

gcd_nat
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...
 18...
 19...
 20...

sqrt_nat
 1...
 2...
 3...
 4...
 5...

compare_big_int
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...

pred_big_int
 1...
 2...
 3...

succ_big_int
 1...
 2...
 3...

add_big_int
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...

sub_big_int
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...

mult_int_big_int
 1...
 2...
 3...
 4...

mult_big_int
 1...
 2...
 3...
 4...
 5...

quomod_big_int
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...
 18...
 19...
 20...
 21...
 22...
 23...
 24...
 25...

gcd_big_int
 1...
 2...
 3...
 4...
 5...
 6...
 7...
 8...
 9...
 10...
 11...
 12...
 13...
 14...
 15...
 16...
 17...
 18...
 19...
 20...
 21...
 22...
 23...
 24...
 25...
 26...
 27...
 28...

int_of_big_int
 1...
 2...
 3...

/home/hugo/local/src/js_of_ocaml/tests/lib-num/test_num.js:699
Q(a){throw[0,K,a]}function
               ^
0,248,Failure,-3,int_of_big_int
```

### PR DESCRIPTION
**Pull request by hhugo**
fix #320 and #865 

Requires some changes in the num library. https://github.com/ocaml/num/pull/16

### CODE REVIEW

File: runtime/nat.js [hunk 1]
```diff
@@ -1,73 +1,96 @@
...
+    { deserialize : deserialize_nat,
+      serialize : serialize_nat
+    }
+}
+
+//Provides: MlNat
+//Requires: caml_hash_mix_int, num_digits_nat
+function MlNat(x){
+  this.data = new joo_global_object.Int32Array(x);
+  this.length = this.data.length + 2
```
Comment (TyOverby) [inline runtime/nat.js]:
```suggestion
  // length_nat isn't external, so we have to make the Obj.size
  // work out right. The +2 to array length seems to work.
  this.length = this.data.length + 2
```
