### PR TITLE
Compiler: modernize js parser

### LINKED ISSUE #508: ES6 Support
http://es6-features.org

related to
- #1031 
- #1017
- #989 
- #972

### LINKED ISSUE #972: [BUG] js_of_ocaml error, cannot parse javascript file (getter syntax)
Using `js_of_ocaml 3.5.2`, my dune builds are failing when I attempt to include this file: https://cdnjs.cloudflare.com/ajax/libs/tensorflow/1.5.2/tf.js .

I narrowed down the problem to this:
```
$ js_of_ocaml --runtime-only tf.js
js_of_ocaml: Error: cannot parse file "tf.js" (orig:"tf.js" from l:22, c:417638)
```

### LINKED ISSUE #989: [BUG] Cannot parse file (trailing comma)
**Describe the bug**
I'm getting an error when compiling a projet :
```
Error: cannot parse file "path/to/harfbuzz.js"
(orig:"path/to/harfbuzz.js" from l:3, c:0)
```

this file contains
```js
// Provides: rehb_new_face
function rehb_new_face(
  _fontName /*: string */,
) {
  return undefined;
}

// Provides: rehb_shape
// Requires: caml_to_js_string
function rehb_shape(_face /*: fk_face */, text /*: string */) {
  var str = caml_to_js_string(text);
  var ret = str.split("").map(function mapper(_char) {
      return [/* <jsoo_empty> */ 0, /* glyphId */ 0, /* cluster */ 0];
    });

  // Adding the leading `0` to make it a jsoo compatible array
  ret.unshift(0);
  return ret;
}
```

I'm thinking this might already have been fixed by #980 , so I tried to pin the latest commit (203dc9c42), but I get a new error. I cannot even build `js_of_ocaml-compiler` anymore, and the dependency build fails with
```
running: 'dune' 'build' '-p' 'js_of_ocaml-compiler' '-j' '4'
           ocaml (internal)
    ocamlfind: Package `graphics' not found
           ocaml (internal) (exit 2)
```

**Versions**
ocaml: 4.08.1
js_of_ocaml: 3.5.2

### LINKED ISSUE #1017: [BUG] javascript parser doesn't handle async/await?
I guess this falls under the general "we don't yet support latest JS", but I though I'd submit it just in case.

**Versions**
3.5.2

**Describe the bug**
```
/home/avatar/.opam/4.09.0/bin/js_of_ocaml: Error: cannot parse file "/home/avatar/docs/webgpu/_build/default/compute/glslang.js" (orig:"/home/avatar/docs/webgpu/_build/default/compute/glslang.js" from l:2, c:8)
```
where the file in question contains
```
async function compile(src)
{
  const glslangModule = await import(
    "https://unpkg.com/@webgpu/glslang@0.0.7/web/glslang.js"
  );
  
  const glslang = await glslangModule.default();
  
  return glslang.compileGLSL(src, "compute");
}

```

### LINKED ISSUE #1031: [BUG] JavaScript parse error (rest parameters ...)
**Describe the bug**
A parse error (`Error: cannot parse file`) is thrown for this piece of code, particularly on the rest parameters in the first line:
```
      api_obj[key_module][key_func] = function(...args) {
        return checkIfInitialized().then(function() {
          return callWithProto(api_json[key_module][key_func], args);
        });
      };
```
Removing the rest parameters notation makes the parsing succeed. This code is part of the [hacl-wasm](https://www.npmjs.com/package/hacl-wasm) npm package.

**Versions**
* ocamlc 4.09.1
* js_of_ocaml 3.6.0

### PR DESCRIPTION
**Pull request by hhugo**
The PR modernize to JavaScript  support inside js_of_ocaml.

The PR started with a synchronization of the jsoo parser with what's found in semgrep
(see https://github.com/returntocorp/semgrep/blob/develop/languages/javascript/menhir/parser_js.mly)

The JS ast was modified to accommodate the new syntaxes.

The PR doesn't change the syntax used during code generation.
Here are a few ideas for the future:
- use arrow function when possible the reduce generated code size
- use `let` for mutable var, instead of using IIFE

### New syntax added in the PR
- destructing `var [x,y] = [1,2]`
- `let` and  `const` and their local scoping
- spread `...`, in expression and patterns
- arrow `(args) => exp`
- `aync/await`
- `yield` and generator
- Bigint
- Nullish coalescing `??`/`.?`
- ForOf
- `get/set/computed` property for object literal
- string templates
- `class`
- `new.target`
- `super`

### Syntax not included in this PR
- `import/export`
- `with` (probably won't fix given it's deprecated)

### X-links
fix #508 
fix #972
fix #989 
fix #1017
fix #1031

unlock #1161 
Replace #1231

### Checklist

- [x] Update ast
- [x] fix scope of `let` and `const`
- [x] Update parser
- [x] Update parser error recovery to handle `( ... ) => .. `
- [x] Check/fix precedence in js_output
- [x] we need better tests for parser/printer (https://github.com/tc39/test262-parser-tests)
- [x] fix variable rewriting for function in object_literal

### CODE REVIEW

**Comment by hhugo** [comment]
@vouillon, the PR is not ready yet but is in an "ok" state if you omit commit history.
Do you think you would be able to help with reviewing and fixing precedence in `js_output.ml` ?

File: compiler/lib/js_output.ml [hunk 1]
```diff
@@ -265,17 +282,21 @@ struct
...
     | Switch_statement _
     | Try_statement _
+    | Function_declaration _
     | Debugger_statement -> false
 
   let rec need_paren l e =
     match e with
-    | ESeq (e, _) -> l <= 0 && need_paren 0 e
-    | ECond (e, _, _) -> l <= 2 && need_paren 3 e
+    | EArrow _ -> Prec.(l <= AssignementExpression)
```
Comment (vouillon) [inline compiler/lib/js_output.ml:290]: Do we really need parentheses in this case?

**Comment by vouillon** [comment]
> @vouillon, the PR is not ready yet but is in an "ok" state if you omit commit history. Do you think you would be able to help with reviewing and fixing precedence in `js_output.ml` ?

I have pushed for fixes

**Comment by hhugo** [comment]
> > @vouillon, the PR is not ready yet but is in an "ok" state if you omit commit history. Do you think you would be able to help with reviewing and fixing precedence in `js_output.ml` ?
> 
> I have pushed for fixes

Thnaks, I've pushed another update to the parser.

**Comment by hhugo** [comment]
Parsing https://github.com/tc39/test262-parser-tests/tree/master/pass

  skip : 254
  fail : 62
  pass : 1667

Most of the remain errors are due to keyword that are meant to be accepted as ident. 
<details>
  <summary>failure details </summary>
```
failed to parse ../test262-parser-tests/pass/ffaf5b9d3140465b.js:1:3
let❌()

failed to parse ../test262-parser-tests/pass/fe2d3b945530c806.js:1:2
a ❌b

failed to parse ../test262-parser-tests/pass/fbcd793ec7c82779.js:1:0
❌<!-- foo

failed to parse ../test262-parser-tests/pass/fa59ac4c41d26c14.js:1:5
({let❌})

failed to parse ../test262-parser-tests/pass/f4a61fcdefebb9d4.js:1:32
var private, protected, public, ❌static

failed to parse ../test262-parser-tests/pass/f2e41488e95243a8.js:1:5
var [❌let] = a;


failed to parse ../test262-parser-tests/pass/f108a85d36ec9afc.js:1:16
({ *a() { yield ❌super.a(); } })

failed to parse ../test262-parser-tests/pass/f0fbbdabdaca2146.js:1:4
var ❌let;


failed to parse ../test262-parser-tests/pass/f0d9a7a2f5d42210.js:1:4
let ❌+ 1

failed to parse ../test262-parser-tests/pass/ee4e8fa6257d810a.js:1:3
let❌++

failed to parse ../test262-parser-tests/pass/e6643a557fe93de0.js:1:7
({yield❌} = 1);

failed to parse ../test262-parser-tests/pass/e5393f15b0e8585d.js:1:5
({let❌} = 1);

failed to parse ../test262-parser-tests/pass/e03ae54743348d7d.js:1:2
--❌> comment

failed to parse ../test262-parser-tests/pass/df696c501125c86f.js:1:7
for(let❌.let in 1);

failed to parse ../test262-parser-tests/pass/d3ac25ddc7ba9779.js:1:0
❌<!--

failed to parse ../test262-parser-tests/pass/d22f8660531e1c1a.js:1:4
var ❌static;

failed to parse ../test262-parser-tests/pass/c8565124aee75c69.js:1:10
for (a of ❌let) {}


failed to parse ../test262-parser-tests/pass/c532e126a986c1d4.js:2:2
;
--❌> HTML comment

failed to parse ../test262-parser-tests/pass/c442dc81201e2b55.js:1:7
for(let❌;;);

failed to parse ../test262-parser-tests/pass/c06df922631aeabc.js:1:13
if (1); else ❌function a(){}

failed to parse ../test262-parser-tests/pass/ba21e63736d8fd46.js:1:3
a: ❌function a(){}

failed to parse ../test262-parser-tests/pass/ba00173ff473e7da.js:1:26
 	 /* block comment */  --❌> comment

failed to parse ../test262-parser-tests/pass/b8c98b5cd38f2bd9.js:1:4
({a:❌let} = 1);

failed to parse ../test262-parser-tests/pass/b563460c1031daf2.js:1:9
({ a() { ❌super.b(); } });

failed to parse ../test262-parser-tests/pass/b15ab152f8531a9f.js:1:0
❌<!-- comment

failed to parse ../test262-parser-tests/pass/aa7e721756949024.js:1:14
({ set a(b) { ❌super.c[1] = 2; } });

failed to parse ../test262-parser-tests/pass/a830df7cf2e74c9f.js:1:13
({ get a() { ❌super[1] = 2; } });

failed to parse ../test262-parser-tests/pass/a5aaa3992025795a.js:1:8
({yield ❌= 1} = 2);

failed to parse ../test262-parser-tests/pass/a4d62a651f69d815.js:1:7
if (a) ❌function b(){}

failed to parse ../test262-parser-tests/pass/a1594a4d0c0ee99a.js:1:13
for (let a = ❌let;;) {}


failed to parse ../test262-parser-tests/pass/9fe1d41db318afba.js:1:8
for(let ❌in 1);

failed to parse ../test262-parser-tests/pass/9f0d8eb6f7ab8180.js:2:4
/*
*/--❌>

failed to parse ../test262-parser-tests/pass/9aa93e1e417ce8e3.js:1:9
for (let ❌in a) {}


failed to parse ../test262-parser-tests/pass/946bee37652a31fa.js:1:21
/* block comment */--❌> comment

failed to parse ../test262-parser-tests/pass/8ec6a55806087669.js:2:3
a = b-->1;
 --❌> nothing

failed to parse ../test262-parser-tests/pass/884e5c2703ce95f3.js:1:10
({ *a() { ❌super.b = 1; } });

failed to parse ../test262-parser-tests/pass/8462f068b299bca2.js:1:8
var {let❌, yield} = 1;

failed to parse ../test262-parser-tests/pass/818ea8eaeef8b3da.js:1:1
(❌let[let])

failed to parse ../test262-parser-tests/pass/7c6d13458e08e1f4.js:1:3
01.❌a

failed to parse ../test262-parser-tests/pass/6b36b5ad4f3ad84d.js:1:3
let❌.let = a


failed to parse ../test262-parser-tests/pass/6815ab22de966de8.js:1:7
for(let❌();;);

failed to parse ../test262-parser-tests/pass/660f5a175a2d46ac.js:1:1
(❌let[a])

failed to parse ../test262-parser-tests/pass/65401ed8dc152370.js:1:4
var ❌let = 1

failed to parse ../test262-parser-tests/pass/6498dcc494193cb4.js:2:2
{1
❌3 4 5}

failed to parse ../test262-parser-tests/pass/63c92209eb77315a.js:1:4
var ❌let

failed to parse ../test262-parser-tests/pass/6196b3f969486455.js:1:0
❌yield => 1

failed to parse ../test262-parser-tests/pass/5ecbbdc097bee212.js:1:10
for (a in ❌let) {}


failed to parse ../test262-parser-tests/pass/5d5b9de6d9b95f3e.js:1:2
--❌>

failed to parse ../test262-parser-tests/pass/5a2a8e992fa4fe37.js:1:5
 	 --❌> comment

failed to parse ../test262-parser-tests/pass/59ae0289778b80cd.js:1:7
if (1) ❌function a(){} else;

failed to parse ../test262-parser-tests/pass/56e2ba90e05f5659.js:1:3
let❌;


failed to parse ../test262-parser-tests/pass/5654d4106d7025c2.js:1:3
let

failed to parse ../test262-parser-tests/pass/52aeec7b8da212a2.js:1:7
if (1) ❌function a(){}

failed to parse ../test262-parser-tests/pass/4f731d62a74ab666.js:1:1
(❌let[a]=b)


failed to parse ../test262-parser-tests/pass/4f5419fe648c691b.js:1:4
  --❌>

failed to parse ../test262-parser-tests/pass/4ae32442eef8a4e0.js:1:0
❌<!--
;

failed to parse ../test262-parser-tests/pass/3dabeca76119d501.js:1:25
try {} catch (a) { if(1) ❌function a(){} }

failed to parse ../test262-parser-tests/pass/2ef5ba0343d739dc.js:1:3
let❌.let

failed to parse ../test262-parser-tests/pass/1c1e2a43fe5515b6.js:1:7
if (1) ❌function a(){} else function b(){}

failed to parse ../test262-parser-tests/pass/14199f22a45c7e30.js:1:4
let ❌= 1;


failed to parse ../test262-parser-tests/pass/1270d541e0fd6af8.js:1:0
❌<!-- HTML comment

failed to parse ../test262-parser-tests/pass/0cf1df0ef867a7f4.js:1:7
({yield❌})
```
</details>

**Comment by hhugo** [comment]
@pmwhite, yet another PR that would happily receive some testing on your side

**Comment by pmwhite** [comment]
Just tested. Some valid javascript like the following got rejected:
```
var y = { async: 35}
              ^
```
at the `c` character, presumably because the parser doesn't think `async` is a valid identifier, since it is a keyword.

**Comment by hhugo** [comment]
> var y = { async: 35}
>               ^

I've just pushed a fix

**Comment by pmwhite** [comment]
Okay, the file that was failing to parse before now succeeds, but the code generated for that file in the output is incorrect. I'm not sure how much to include, but I _think_ the relevant part of the input and output files is this translation:

Input:
```
{key:"from",
 value:
   function from(field,get)
     {if(!get)get=function get(x){return x;};
      return this.compute([field],function(state){return get(state.field(field));});}}
```

Output:
```
{key:"from",
 value:
   function get(field,get)
     {if(! get)get = function(x){return x};
      return this.compute([field],function(state){return get(state.field(field))})}}
```

The bug manifests itself at runtime with an error like "`Stuff.get` is not a function"; in the original input file, however, the code calls `Stuff.from` instead of `get`, so I guess there is a translation happening at both the caller and callee; I don't know which one is the incorrect one.

**Comment by hhugo** [comment]
@pmwhite, bug fixed by https://github.com/ocsigen/js_of_ocaml/pull/1391/commits/a153a3a825e22402422b1d8b78efb7a597d5add4

File: compiler/tests-compiler/js_parser_printer.ml [hunk 2]
```diff
@@ -445,6 +445,34 @@ let%expect_test "string template" =
...
+
+  [%expect
+    {|
+    /*<< 2 0>>*/ ({key:"from",
+     value:
+     function get(field,get)
+      { /*<< 5 6>>*/ if(! get)
+         /*<< 5 14>>*/ get
+        =
+        function get(x){ /*<< 5 34>>*/ return x /*<< 5 18>>*/ };
```
Comment (pmwhite) [inline compiler/tests-compiler/js_parser_printer.ml:469]: This test is failing for me. I believe this test is demonstrating the bug, rather than the fix.

**Comment by hhugo** [comment]
I've added some support for `class`, only leaving `import` and `export` unsupported.

**Comment by pmwhite** [comment]
Oh, that's awesome. Just tested again on the new commits and found no issues.

**Comment by TyOverby** [comment]
> Parsing https://github.com/tc39/test262-parser-tests/tree/master/pass

@hhugo could we pull this into the repo and have them build automatically as part of the test suite?

**Comment by hhugo** [comment]
I think so, but work is needed to have good integration.

**Comment by tpetr** [comment]
@hhugo thanks so much for this PR! Could you publish a new release to opam so that I can unblock myself in https://github.com/returntocorp/semgrep/pull/7220?

**Comment by hhugo** [comment]
@tpetr, there is at least one more PR that I'd like include in the next release. 
See https://github.com/ocsigen/js_of_ocaml/milestone/10.
